### PR TITLE
Improve warnings and error messages

### PR DESCRIPTION
**Pull request by Jummit**
Add messages that explain the warning instead of just dumping the error code. This also removes the warning that says to change the settings. Maybe this could be noted somewhere else, like the github Readme or a small warning inside the UI.

### CODE REVIEW

**Comment by AlexDarigan** [comment]
Going to wait on this one until I'm done in my refactoring branch because I could foresee a future conflict.

**Comment by Jummit** [comment]
Can I resolve conflicts and make it ready to merge?

**Comment by AlexDarigan** [comment]
Just merged dev to main. 

Note: test_gatherer has been replaced by filesystem.

**Comment by AlexDarigan** [comment]
You'll see some godot errors about buttons not valid etc on run. I have to get around to fixing up the asset scale updaters so don't worry about those.

**Comment by Jummit** [comment]
Done.

**Comment by AlexDarigan** [comment]
Thanks.

**Pull request merged**
